#!/usr/bin/env bash

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
status=0

#URL='https://www.accuweather.com/en/us/kent-oh/44240/weather-forecast/339994'
URL='https://www.accuweather.com/en/us/lexington-oh/44904/weather-forecast/2086396'
USER_AGENT="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36"
SITE="$(curl -H "$USER_AGENT" -s "$URL")"

weather="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $13 }'| head -1)"
temp="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $10 }'| head -1)"

if [[ $weather == *thunder* || $weather == *Thunder* ]]; then
	icon=" "
else
	if [[ $weather == *rain* || $weather == *Rain* ]]; then
        icon=""
else
	if [[ $weather == *snow* || $weather == *Snow* ]]; then
                icon=""
else
	if [[ $weather == *cloud* || $weather == *Cloud* ]]; then
		icon=""
else
		icon=""
			fi
		fi
	fi
fi

# Does not display if there's not temperature to display
if [ -z $temp ]; then
	full=""
	short=""
else
	cel=$(( ( $temp - 32 ) * 5 / 9 ))
	full="$icon $temp°($cel)"
	short="$temp°"
fi

# Left, Middle, Right, Up, Down
case $BLOCK_BUTTON in
1) gnome-weather --class floater;;
2) ;;
3) xdg-open "https://www.wunderground.com/us/oh/kent" 1>/dev/null|| :;;
4) ;;
5) ;;
esac

echo $full
exit $status
